# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
  - "pypy"

# command to install dependencies
install: pip install -U .

# command to run tests, e.g. python setup.py test
script: py.test
